[Variables]
Alignment=Left
; The alignment of the skin inside of the skin area.
; Valid values are "Left", "Center" and "Right".

HideBattery=False
; Hide the battery icon or not. Useful setting for desktop PCs.
; Valid values are "True" and "False".

BatteryPercentageStyle=None
; The style of the battery percentage.
; Valid values are "None", "InBattery" and "NextToBattery".

; ================================================

Scale=1.00
; The scale of the skin. Acts as a multiplier for the width and height of everything.

Width=240
; The total maximum width of the skin (hold Ctrl + Alt and click on the skin to see the skin area).

TimeSize=96
DateSize=32
; The size of the time and date text in pixels.

TimeFontOffset=48
; Change the offset between the hour and minute text, so you can bring them closer together. Each font is different, so change this value at will.
; The higher the number, the closer the two meters are to each other.

; ================================================

TimeFont=Oswald
DateFont=Roboto Flex Normal
; The fonts used for the time and date text.

Color=255, 255, 255
; The color of the text and battery icon.
; Valid values are formatted "RRR, GGG, BBB".
